---

- include_tasks: variables.yml

- include_tasks: assertions.yml

- include_tasks: "{{ ansible_os_family }}/install.yml"

- include_tasks: easy-rsa.yml

- include_tasks: clients.yml

- include_tasks: configure.yml

- include_tasks: firewall.yml

- include_tasks: service.yml
