---

- name: Include OS-specific variables.
  include_vars: "{{ lookup('first_found', paths) }}"
  vars:
    paths:
      - "vars/{{ ansible_distribution }}.{{
            ansible_lsb.codename | default(omit)}}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}.yml"
      - "vars/Common-default.yml"

- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.yum.yml
  when: ansible_os_family == 'RedHat'

- include: configure.yml

- include: setup-bridge.deb.yml
  when: ansible_os_family == 'Debian'

- include: setup-bridge.rh.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure OpenVPN is started
  service:
    name: "{{ openvpn_service }}"
    state: started
    enabled: true
