---

- name: Setup simple authentication
  template:
    src: authentication/auth-client.sh.j2
    dest: "{{ openvpn_etcdir }}/auth-client.sh"
    mode: 0o755
  when:
    - openvpn_simple_auth | bool
    - openvpn_simple_auth_password | bool
  notify: openvpn restart
